jealous/stockstats

README.rst, stockstats.py, test.py
=> Correct MACDH calculation and adds warning about change.

.gitignore, .travis.yml, README.rst, setup.py, stockstats.py, test-requirements.txt, test.py
Enhancements:
* [GH-19] Extract default indicator windows to class-level variables.
* [GH-21] Support for TEMA.
* [GH-22] Add support to count forward.
* Add platform test for 3.6, 3.7
* Change coverage service provider to `codecov.io`
This closes GH-19, GH-21, and GH-22.
=> Release 0.3.0.

README.rst
TEMA and TRIX can be adjusted with customized window.  Add sample in the
README.
=> [GH-47] Add sample for TEMA and TRIX.

stockstats.py
General enhancement by adding docstring to _get_change method
=> Added docstring to _get_change method

test-requirements.txt
Upgrade the pytest version to meet the requirement of pytest_cov.
=> Upgrade pytest version.

README.rst, stockstats.py, test.py
I implemented the money flow index for stockstats. It will provide constant values of 0.5 if no volume data is available.
=> implement money flow index

.travis.yml, stockstats.py
Migrate from travis.org to travis.com.  Fix several format issues in the
build.  Remove the check for python 3.5 and 3.6.
=> [GH-79] Fix build failure in travis com

README.rst, stockstats.py, test.py
I made a small mistake in my mfi indicator contribution, which i want to rectify. 
I have expanded the tests by adding an example that i calculated by hand as to make sure it works correctly now.
=> MFI indicator minor bugfix

.travis.yml, requirements.txt, stockstats.py, test.py
As title.  Also update to the latest pandas for python27.
=> Fix python27 build error for MFI

stockstats.py, test.py
The WR results should be negative numbers.
Replace `* 100` with `* -100`.
=> [GH-60] WR result should be negative

.github/workflows/build-test.yml, stockstats.py, test.py, tox.ini
Add support for PPO(Percentage Price Oscillator).
User can change the default PPO window with:
```
PPO_EMA_SHORT = 12
PPO_EMA_LONG = 26
PPO_EMA_SIGNAL = 9
```
=> [GH-8] Add PPO support

stockstats.py, test.py
Add StochRSI.  The default window is set to 14.
Use `StockDataFrame.RSI` to change it.
Add wave trand that includes two lines.  The default window of the ema
is set to `10` and `21`.
Use `StockDataFrame.WAVE_TREND_1` and `StockDataFrame.WAVE_TREND_2` to
change them.
=> [GH-76] Add StochRSI and wave trend

README.md, stockstats.py, test.py
Use `init_all` to initialize all indicators with shortcuts.
=> [GH-11] Retrieve all indicators

README.md, stockstats.py, test.py
As title.  Also fix some issues in readme.
=> [GH-23] Add supertrend indicator.

README.md, stockstats.py, test.py
Add a window parameter for bollinger. User could specify the customized window in the column name, such as `boll_5`.
=> [GH-133] Support boll window in col. name

README.md, stockstats.py, test.py
Allow user to calculate the Z-Score of a column with column name and window.
=> [GH-137] Support Z-Score

README.md, stockstats.py, test.py
Add Balance of Power.
Balance of Power (BOP) measures the strength of the bulls vs. bears.
Formular:
```
BOP = (close - open) / (high - low)
```
Example:
* `df['bop']` returns the Balance of Power
=> [GH-141] Add BOP

README.md
=> [GH-187] Update version to 0.6.3

README.md
=> Set version to 0.6.4

README.md
=> Update release to 0.6.5
