jealous/stockstats

.travis.yml
README.rst
setup.py
stockstats.py

Pandas 1.0 introduces a `_ensure_type` method that asserts the type of
`self` must be the same type as the input `obj`.  In this lib, the type
of `self` is `StockDataFrame` and the type of the object is `DataFrame`
which breaks this assert.
The temporary fix is to bypass the assert by override the `_ensure_type`
method in `StockDataFrame`.  The is just a work around.  The good news
is that the original method doesn't contain any business logic.
Other changes:
* Update the travis configuration to add CI for python 3.8.
* Drop the CI build for 3.4.  It's too old and takes too long to run.

[GH-50] Pandas 1.0 compatible issue.

---

.travis.yml
README.rst
stockstats.py
test.py

Fix the warnings in the lib, including:
* modify the data in-place
* replace `contains` with `contains_exactly` in the test
* remove the `MACDH` warning.

[GH-62] Fix warnings

---

README.rst
stockstats.py
test.py

The indicator was tested against the reference [investopedia article](https://school.stockcharts.com/doku.php?id=technical_indicators:kaufman_s_adaptive_moving_average). It has more settings than other indicators, so the name could be parsed into five parts now.
_close_10_kama_2_30_
has three settings:
- _10 is the number of periods for the Efficiency Ratio (ER)._
- _2 is the number of periods for the fastest EMA constant._
- _30 is the number of periods for the slowest EMA constant._
To make sure regular indicators are parsed as usual, only those within the tuple MULTI_SPLIT_INDICATORS will be parsed into five parts.

Add Kaufman Adaptive Moving Average

---

requirements.txt
stockstats.py
test.py

The calculation of the `mfi` indicator takes seconds.
Enhance the algorithm to improve the performance.
Reduce the size of the test to make shorten the duration of the tests.
Remove some dead code.

[GH-94] Improve mfi performance

---

stockstats.py
test.py

Add support for volume weighted moving average.
See the definition here:
https://www.investopedia.com/articles/trading/11/trading-with-vwap-mvwap.asp
Users can assess this value with `df['vwma']`
The default period is set to 14.
Users can specify the customized period with `df['vwma_5']`.

[GH-67] Add VWMA support

---

stockstats.py
test.py

Support Choppiness Index (CHOP)
See the definition of the index here:
https://www.tradingview.com/education/choppinessindex/
Calculation:
* 100 * LOG10( SUM(ATR(1), n) / ( MaxHi(n) - MinLo(n) ) ) / LOG10(n)
* n = User defined period length.
* LOG10(n) = base-10 LOG of n
* ATR(1) = Average True Range (Period of 1)
* SUM(ATR(1), n) = Sum of the Average True Range over past n bars
* MaxHi(n) = The highest high over past n bars

[GH-70] Add support for CHOP index

---

setup.py
stockstats.py
test.py

During the calculation of the KAMA, we should use
```
fastest SC - slowest SC
```
instead of
```
fastest SC + slowest SC
```

[GH-102] Fix KAMA smoothing error.

---

stockstats.py
test.py

Duration the calculation of some indicators, we create some intermediate
results in the data frame.  Some of them are removed before we finish.
It brings two problems:
* It caches extra columns that user may not need in the memory.
* It may accidently cleanup the columns created by the user.
Fix the issue by not caching the result in user's data frame.

[GH-74] Eliminate intermediate results

---

README.md

[GH-112] Fix minor errors in readme.

---

README.md

Just fixed a typo in stochastic oscillator examples.

Fixing typo in readme - stochastic oscillator examples

---

.github/workflows/build-test.yml
README.md
stockstats.py
test.py

The typical price or middle price is calculated by:
```
(high + low + close) / 3
```
But it would be accurate if the data source has the `amount` that represents the total amount of capital traded in that period. Use `middle = amount / volume` when amout is available.
Also fix some typos in the read me file.
Add some utilities for dropping columns, head or tail.
Add python 3.11 in CI and drop 3.9.

[GH-122] Update calculation of `middle`

---

README.md
stockstats.py
test.py

When user specify a customized window for the energy index, it should appear in the column name. The customized column should not overwrite the column with the default window size.

[GH-130] CR window is not in the name.

---

README.md
stockstats.py
test.py

Add aroon oscillator.
* Aroon Oscillator = Aroon Up - Aroon Down
* Aroon Up = 100 * (n - periods since n-period high) / n
* Aroon Down = 100 * (n - periods since n-period low) / n
* n = window size
https://www.investopedia.com/terms/a/aroonoscillator.asp
The default window is 25.

[GH-121] Add Aroon indicator

---

README.md
setup.py
stockstats.py
test.py

The AO indicator is a good indicator for measuring the market dynamics, it reflects specific changes in the driving force of the market, which helps to identify the strength of the trend, including the points of its formation and reversal.
Awesome Oscillator Formula
* MEDIAN PRICE = (HIGH+LOW)/2
* AO = SMA(MEDIAN PRICE, 5)-SMA(MEDIAN PRICE, 34)
Examples:
* `df['ao']` returns the Awesome Oscillator with default windows (5, 34)
* `df['ao_3,10']` returns the Awesome Oscillator with a window of 3 and 10

[GH-139] Add Awesome Oscillator

---

README.md
stockstats.py
test.py

The Chande Momentum Oscillator (CMO) is a technical momentum indicator developed by Tushar Chande.
https://www.investopedia.com/terms/c/chandemomentumoscillator.asp
```
CMO = 100 * ((sH - sL) / (sH + sL))
```
where:
* sH=the sum of higher closes over N periods
* sL=the sum of lower closes of N periods

[GH-143] Retrieve Chande Momentum Oscillator

---

README.md
stockstats.py
test.py

Coppock Curve is a momentum indicator that signals long-term trend reversals.
Formular:
Coppock Curve = 10-period WMA of (14-period RoC + 11-period RoC) WMA = Weighted Moving Average
RoC = Rate-of-Change
Examples:
* `df['coppock']` returns the Coppock Curve with default windows
* `df['coppock_5,10,15']` returns the Coppock Curve with WMA window 5, fast window 10, slow window 15.

[GH-145] Add Coppock Curve

---

README.md
stockstats.py
test.py

The Ichimoku Cloud is a collection of technical indicators that show support and resistance levels, as well as momentum and trend direction.
In this implementation, we only calculate the delta between lead A and lead B (which is the width of the cloud).
It contains three windows:
* window for the conversion line, default to 9
* window for the baseline and the shifts, default to 26
* window for the leading line, default to 52
Formular:
* conversion line = (PH9 + PL9) / 2
* baseline = (PH26 + PL26) / 2
* leading span A = (conversion line + baseline) / 2
* leading span B = (PH52 + PL52) / 2
* result = leading span A - leading span B
Where:
* PH = Period High
* PL = Period Low
Examples:
* `df['ichimoku']` returns the ichimoku cloud width with default windows
* `df['ichimoku_7,22,44']` returns …

[GH-116] Add ichimoku cloud width

---

.github/workflows/build-test.yml
setup.py
stockstats.py
test.py

The directional movement index should be calculated with smoothed moving average.
Also update the calculation so that we don't generate extra columns.

[GH-150] Fix pdm and ndm

---

README.md
stockstats.py
test.py

The Efficiency Ratio (ER) is calculated by
dividing the price change over a period by the
absolute sum of the price movements that occurred
to achieve that change.
The resulting ratio ranges between 0 and 1 with
higher values representing a more efficient or
trending market.
The default column is close.
The default window is 10.
Formular:
* window_change = ABS(close - close[n])
* last_change = ABS(close-close[1])
* volatility = moving sum of last_change in n
* KER = window_change / volatility
Examples:
* `df['ker']` retrieves the 10 periods KER of the close price
* `df['high_5_ker']` retrieves 5 periods KER of the high price

[GH-152] Extract Kaufman's Adaptive Moving Average

---

README.md
stockstats.py
test.py

The Elder-Ray Index contains the bull and the bear power. Both are calculated based on the EMA of the close price.
The default window is 13.
Formular:
* Bulls Power = High - EMA
* Bears Power = Low - EMA
* EMA is exponential moving average of close of N periods
Examples:
* `df['eribull']` retrieves the 13 periods bull power
* `df['eribear']` retrieves the 13 periods bear power
* `df['eribull_5']` retrieves the 5 periods bull power
* `df['eribear_5']` retrieves the 5 periods bear power

[GH-154] Add Elder-Ray Index

---

README.md
stockstats.py
test.py

Extract a utility class `_Meta` to handle the periods and column names.
Remove the default periods in the class member and put them in a dictionary.
Change the way to update the default windows.

[GH-156] Add _Meta utility class

---

README.md
stockstats.py
test.py

The Gaussian Fisher Transform Price Reversals indicator, dubbed FTR for short, is a stat based price reversal detection indicator inspired by and based on the work of the electrical engineer now private trader John F. Ehlers.
https://www.tradingview.com/script/ajZT2tZo-Gaussian-Fisher-Transform-Price-Reversals-FTR/
Implementation reference:
https://github.com/twopirllc/pandas-ta/blob/084dbe1c4b76082f383fa3029270ea9ac35e4dc7/pandas_ta/momentum/fisher.py#L9
Formular:
* Fisher Transform = 0.5 * ln((1 + X) / (1 - X))
* X is a series whose values are between -1 to 1
Examples:
* `df['ftr']` returns the FTR with window 9
* `df['ftr_20']` returns the FTR with window 20

[GH-158] Gaussian Fisher Transform Price Reversals

---

README.md
stockstats.py
test.py

The Relative Vigor Index (RVI) is a momentum indicator used in technical analysis that measures the strength of a trend by comparing a security's closing price to its trading range while smoothing the results using a simple moving average (SMA).
https://www.investopedia.com/terms/r/relative_vigor_index.asp
Formular
* NUMERATOR= (a+(2×b)+(2×c)+d) / 6
* DENOMINATOR= (e+(2×f)+(2×g)+h) / 6
* RVI= SMA-N of DENOMINATOR / SMA-N of NUMERATOR
* Signal Line = (RVI+(2×i)+(2×j)+k) / 6
where:
* a=Close−Open
* b=Close−Open One Bar Prior to a
* c=Close−Open One Bar Prior to b
* d=Close−Open One Bar Prior to c
* e=High−Low of Bar a
* f=High−Low of Bar b
* g=High−Low of Bar c
* h=High−Low of Bar d
* i=RVI Value One Bar Prior
* j=RVI Value One Bar Prior to i
* k=RVI Value One Bar Prior to j
* …

[GH-160] Add Relative Vigor Index

---

README.md
stockstats.py
test.py

In financial markets, the concept of inertia was given by Donald Dorsey in the 1995 issue of Technical Analysis of Stocks and Commodities through the Inertia Indicator. The Inertia Indicator is moment-based and is an extension of Dorsey’s Relative Volatility Index (RVI).
Formular:
* inertia = n periods linear regression of RVGI
Examples:
* `df['inertia']` retrieves the inertia of 20 periods linear regression of 14 periods RVGI
* `df['inertia_10']` retrieves the inertia of 10 periods linear regression of 14 periods RVGI

[GH-163] Add Inertia Indicator

---

README.md
stockstats.py
test.py

The Know Sure Thing (KST) is a momentum oscillator developed by Martin Pring to make rate-of-change readings easier for traders to interpret.
https://www.investopedia.com/terms/k/know-sure-thing-kst.asp
Formular:
* KST=(RCMA1×1)+(RCMA2×2) + (RCMA3×3)+(RCMA4×4)
Where:
* RCMA1=10-period SMA of 10-period ROC
* RCMA2=10-period SMA of 15-period ROC
* RCMA3=10-period SMA of 20-period ROC
* RCMA4=15-period SMA of 30-period ROC

[GH-165] Add Know Sure Thing support

---

README.md
stockstats.py
test.py

The Pretty Good Oscillator indicator by Mark Johnson measures the distance of the current close from its N-day simple moving average, expressed in terms of an average true range over a similar period.
https://library.tradingtechnologies.com/trade/chrt-ti-pretty-good-oscillator.html
Formular:
* PGO = (Close - SMA) / (EMA of TR)
Example:
* `df['pgo']` retrieves the PGO with default window 14.
* `df['pgo_10']` retrieves the PGO with window 10.

[GH-167] Add Pretty Good Oscillator Support

---

README.md
stockstats.py
test.py

The Psychological Line indicator is the ratio of the number of rising periods over the total number of periods.
https://library.tradingtechnologies.com/trade/chrt-ti-psychological-line.html
Formular:
* PSL = (Number of Rising Periods) / (Total Number of Periods) * 100
Example:
* `df['psl']` retrieves the PSL with default window 12.
* `df['psl_10']` retrieves the PSL with window 10.
* `df['high_12_psl']` retrieves the PSL of high price with window 10.

[GH-169] Add Psychological Line (PSL) Support

---

README.md
stockstats.py
test.py

The Percentage Volume Oscillator (PVO) is a momentum oscillator for volume. The PVO measures the difference between two volume-based moving averages as a percentage of the larger moving average.
https://school.stockcharts.com/doku.php?id=technical_indicators:percentage_volume_oscillator_pvo
Formular:
* Percentage Volume Oscillator (PVO): ((12-day EMA of Volume - 26-day EMA of Volume)/26-day EMA of Volume) x 100
* Signal Line: 9-day EMA of PVO
* PVO Histogram: PVO - Signal Line

[GH-171] Add support for PVO

---

README.md
stockstats.py
test.py

The Qualitative Quantitative Estimation (QQE) indicator works like a smoother version of the popular Relative Strength Index (RSI) indicator. QQE expands on RSI by adding two volatility based trailing stop lines. These trailing stop lines are composed of a fast and a slow moving Average True Range (ATR). These ATR lines are smoothed making this indicator less susceptible to short term volatility.
Implementation reference:
https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/momentum/qqe.py
Example:
* `df['qqe']` retrieves the QQE with RSI window 14, MA window 5.
* `df['qqel']` retrieves the QQE long
* `df['qqes']` retrieves the QQE short
* `df['qqe_10,4']` retrieves the QQE with RSI window 10, MA window 4
* `df['qqel_10,4']` retrieves the QQE long with customized windows. …

[GH-173] Support QQE

---

README.md
stockstats.py
test.py

The initial value of z-score is set to 0, which breaks the kdj calucation.  We should use the first valid value to fill the gap.

[GH-175] z-score based kdj is invalid.

---

stockstats.py

1st commit implements the compare function itself.
2nd commit implements `_get_num()` for filling in numerical values (e.g. `num_10` for 10.0 and `num_10,01` for 10.01).
Merge it if you wish.
One thing to note, I am getting the following warning:
```
PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
self[key] = self[left] < self[right]
```
I am not sure when it started appearing but I don't think it was there before the second commit so it needs further testing. Other than that everything seems to be working properly, I kept my changes minimal.

Numerical comparison implemented

---

stockstats.py

Adjusting supertrend evaluation by comparing previous close value instead of current
Link to [the issue](https://github.com/jealous/stockstats/issues/125) (I am unable to link them direcly over github).

Fix issue 125 - Supertrend misscalculation

---

.github/workflows/build-test.yml
stockstats.py

Pandas report warning when we retrieve/initialize multiple columns with following syntax:
```python
df[['kdjk', 'kdjj']]
```
Update the call of the `rename` function to use return value instead of inplace change to avoid this warning.

[GH-190] copy slice warn getting multiple cols

---

stockstats.py
test.py

The shift function cannot accept empty series.
The reason is we use previous/next value to fill the empty cell. An empty data frame results in a invalid index error.
The fix returns the empty series.

[GH-193] Shift an series frame raise error
